apiVersion: v1
kind: Service
metadata:
  name: microservices-app
  labels:
    app: microservices-app
spec:
  type: LoadBalancer
  selector:
    app: microservices-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
