name: Terraform Azure Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
      environment:
        description: "Select deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write   # Required for OIDC
  contents: read

env:
  TF_VERSION: 1.8.5
  TF_WORKING_DIR: ./terraform

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action }} (${{ github.event.inputs.environment }})
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Azure with OIDC
      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      #  Step 4: Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      # 🧮 Step 5: Terraform Plan / Apply / Destroy
      - name: Terraform ${{ github.event.inputs.action }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          case "${{ github.event.inputs.action }}" in
            plan)
              terraform plan -input=false -out=tfplan
              ;;
            apply)
              terraform apply -input=false -auto-approve tfplan || terraform apply -input=false -auto-approve
              ;;
            destroy)
              terraform destroy -input=false -auto-approve
              ;;
            *)
              echo "Invalid action"; exit 1;
              ;;
          esac

      # 🧪 Step 6: Post-deployment check
      - name: Verify Azure Context
        run: az account show
